services:
  property_management_back_app:
    container_name: property_management_back_app
    image: kevincrisa/property_management_back_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@property_management_back_db:5432/postgres
    depends_on:
      - property_management_back_db
  property_management_back_db:
    container_name: property_management_back_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
